# Generated by Django 3.1.7 on 2021-03-24 15:08

from django.db import migrations

def create_data(apps, schema_editor):
    Users = apps.get_model('users', 'Users')
    Users(name = "Users 001", email="users001@email.com", phone="00000000", address="Users 000 Address", description="Users 001 description").save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
